(() => {
  "use strict";

  const manifest = window.__OMNIMIND_REMOTE_MANIFEST__ || {};
  const VERSION = manifest.version || "4.0.2-sync";
  if (window.__OMNIMIND_REMOTE_OVERLAY_VERSION__ === VERSION) return;
  window.__OMNIMIND_REMOTE_OVERLAY_VERSION__ = VERSION;

  const PAGE = Object.freeze({
    home:{id:"OM-P01",route:"/home",phase:"OBSERVABILITY CORE",purpose:"Explain the whole estate in under ten seconds.",zones:["Executive metrics with source and freshness","Current operating truth and highest blocker","Estate topology preview","Feature and mission queue","Proof stream","One precise action launchpad"],tasks:["Replace hardcoded metrics with shared projections","Attach source, observed time and freshness to every state","Project first eligible safe action","Preserve offline and stale truth","Bind ProofGrid receipts and human gates"],gate:"Repository composition active; physical F02 reconnect remains open."},
    pairing:{id:"OM-P02",route:"/command/pairing",phase:"COMMAND PATHWAY",purpose:"Establish and inspect trust between human, phone, package and EDEN.",zones:["Current device and signing identity","Gateway identity and fingerprint","Pairing ceremony state machine","Trusted devices","Signed reconnect evidence","Revocation and recovery"],tasks:["Request challenge","Display exact fingerprint","Require explicit approval","Sign with device key","Verify gateway response","Seal signed reconnect receipt","Preserve expiry, replay, signature and revocation failures"],gate:"Physical pairing approval and signed reconnect required before F03 execution."},
    navi:{id:"OM-P03",route:"/command/navi",phase:"COMMAND PATHWAY",purpose:"Turn human language into deterministic structured intent.",zones:["Multiline command composer","Interpretation and ambiguity","Existing-organ routing","Safety and authority preview","Suggested next command"],tasks:["Bind drafts and history","Normalize intent, target and exclusions","Clarify ambiguity instead of guessing","Separate preview from execution","Export structured command object","Preserve parsing and routing failures"],gate:"Preview available; live execution remains locked behind F02."},
    atlas:{id:"OM-P04",route:"/command/atlas",phase:"COMMAND PATHWAY",purpose:"Convert intent into a bounded mission blueprint.",zones:["Mission summary","Scope plan","Ordered construction steps","Risk and blast radius","Proof plan","Rollback plan"],tasks:["Use one mission identity","Require explicit targets and exclusions","Define acceptance tests","Define proof requirements","Attach recovery coordinate","Request bounded authority"],gate:"Mission may not advance without complete scope, proof and recovery requirements."},
    janus:{id:"OM-P05",route:"/command/janus",phase:"COMMAND PATHWAY",purpose:"Grant, reduce, defer or deny bounded authority.",zones:["Mission awaiting decision","Policy evaluation","Approval ceremony","Replay protection","Decision history"],tasks:["Verify identity and F02 state","Evaluate risk and dependencies","Require nonce and expiry","Support reduced-scope approval","Preserve every decision","Emit existing ProofGrid authority receipt"],gate:"Biometric or explicit human approval required where policy demands it."},
    packets:{id:"OM-P06",route:"/command/packets",phase:"COMMAND PATHWAY",purpose:"Represent commands as signed, inspectable packets.",zones:["Packet envelope","Mission payload","Capability scope","Signature verification","Lifecycle timeline","Related evidence"],tasks:["Validate signer","Validate nonce and expiry","Reject unapproved capabilities","Project lifecycle truth","Attach approval, execution, failure and recovery evidence"],gate:"Accepted is impossible unless identity, signature, scope, nonce and expiry pass."},
    estate:{id:"OM-P07",route:"/estate/control-plane",phase:"OBSERVABILITY CORE",purpose:"Show the living topology of the Ghost Atlas estate.",zones:["18-organ topology","Organ registry","Typed relationship edges","Estate event stream","Organ inspector","Snapshot comparison"],tasks:["Source every organ state","Record observed time and freshness","Separate implementation from runtime state","Expose dependencies and failures","Support mobile topology","Bind proof and recovery coordinates"],gate:"No green organ state without source and observation time."},
    workforce:{id:"OM-P08",route:"/estate/workforce",phase:"OBSERVABILITY CORE",purpose:"Control campaigns, dependencies, gates and failed evidence.",zones:["Campaign board","F02-F07 dependency graph","First eligible action","Failed evidence registry","Human gate board","No-safe-transition state"],tasks:["Enforce strict dependency order","Compute one next safe action","Preserve all failed attempts","Display exact human action","Prevent later features from clearing early"],gate:"F03 remains physically locked until F02 signed reconnect is verified."},
    github:{id:"OM-P09",route:"/engineering/github",phase:"ENGINEERING AND VERIFICATION",purpose:"Trace source through commits, PRs, workflows and artifacts.",zones:["Repository selector","Commit inspector","PR inspector","Workflow inspector","Artifact registry","Release registry"],tasks:["Record exact SHAs","Distinguish zero-step infrastructure failure from test failure","Attach logs and artifacts","Bind signer and digests","Compare candidate versus promoted release","Preserve failed evidence"],gate:"A release must trace to exact source and proof."},
    sdlc:{id:"OM-P10",route:"/engineering/sdlc",phase:"ENGINEERING AND VERIFICATION",purpose:"Show one mission from discovery through closure.",zones:["15-stage lifecycle","Stage inspector","Blocked-stage view","Evidence completeness","Rollback path","Handoff history"],tasks:["Define entry and exit criteria for every stage","Attach responsible organs and outputs","Prevent early completion","Show first blocked stage","Bind timestamps, failures and receipts"],gate:"No stage completes without its required output and evidence."},
    prometheus:{id:"OM-P11",route:"/verification/prometheus",phase:"ENGINEERING AND VERIFICATION",purpose:"Challenge, repair and recommend verified candidates.",zones:["Candidate registry","Test matrix","Adversarial challenge","Repair history","Promotion recommendation","Limitations and rollback"],tasks:["Use exact candidate source identities","Run applicable test classes","Preserve adversarial failures","Retest repairs","Emit proof-backed recommendation","Never grant final promotion authority"],gate:"Recommendation only; final promotion remains human governed."},
    seca:{id:"OM-P12",route:"/verification/seca",phase:"ENGINEERING AND VERIFICATION",purpose:"Determine whether work is actually finished.",zones:["Requirement coverage","Missing evidence","Contradictions","Readiness states","Closure verdict"],tasks:["Derive verdict from evidence","Keep repository, artifact, deployment and physical truth separate","Expose exact missing action","Preserve contradictions","Reject manually painted green states"],gate:"Final closure requires physical evidence and reproducible proof."},
    medusa:{id:"OM-P13",route:"/verification/medusa",phase:"ENGINEERING AND VERIFICATION",purpose:"Bound identities, secrets, networks and dangerous capabilities.",zones:["Identity posture","Secret posture","Network posture","Capability boundaries","Incident controls"],tasks:["Never expose raw secrets","Map every mutation to identity and approval","Show bind exposure","Preserve incident evidence","Keep Sovereign Stop reachable","Provide quarantine and recovery path"],gate:"Every mutating capability requires trusted identity, authority and evidence."},
    proof:{id:"OM-P14",route:"/proof/proofgrid",phase:"OBSERVABILITY CORE",purpose:"Inspect receipts and the chain from intent to outcome.",zones:["Receipt stream","Chain graph","Receipt inspector","Failure evidence","Digest validation","Proof export"],tasks:["Bind existing ProofGrid formats","Detect gaps, duplicates and contradictions","Verify signatures and digests","Keep failure receipts first class","Export mission and release bundles"],gate:"PAGE_CLEARED requires existing ProofGrid evidence, not a new receipt format."},
    thoth:{id:"OM-P15",route:"/proof/thoth",phase:"PROOF CONTINUITY",purpose:"Preserve searchable lineage and changing truth.",zones:["Search","Lineage graph","Memory inspector","Contradiction registry","Supersession ledger"],tasks:["Search by object, mission, SHA, artifact and receipt","Preserve prior truth","Link created-from and recovered-from relationships","Support offline lineage inspection","Attach existing receipts"],gate:"Current state must be reconstructable without conversation memory."},
    osiris:{id:"OM-P16",route:"/proof/osiris",phase:"PROOF CONTINUITY",purpose:"Recover repositories, artifacts, configuration and device state.",zones:["Recovery inventory","Recovery planner","Restore points","Rollback approval","Execution history","Failed recovery evidence"],tasks:["Record known-good source and artifact","Define rollback-of-rollback","Protect destructive recovery","Test recovery coordinates","Preserve failed recovery attempts"],gate:"Rollback approval required for protected recovery."},
    metaforge:{id:"OM-P17",route:"/publication/metaforge",phase:"PROOF CONTINUITY",purpose:"Explain exactly how each artifact was created.",zones:["Source materials","Locked dependencies","Toolchain","Build recipe","Environment references","Outputs and reproducibility"],tasks:["Record exact source and tool versions","Keep secrets referenced, not exposed","Attach digest, size and signature","Classify reproducibility","Support trusted-builder recreation"],gate:"Artifact provenance must be auditable from source to signature."},
    serverforge:{id:"OM-P18",route:"/publication/serverforge",phase:"DELIVERY PATHWAY",purpose:"Control private and public-safe publication.",zones:["Publication channels","Audience classification","Publication object","Delivery stream","Public-safe proof boundary"],tasks:["Separate private proof from public proof","Require approval","Track queued through acknowledged states","Preserve publication failures","Keep boot independent of public hosting"],gate:"No material leaves the private estate without classification and approval."},
    mobile:{id:"OM-P19",route:"/operations/mobile",phase:"DELIVERY PATHWAY",purpose:"Make the phone a resilient operating surface.",zones:["Device diagnostics","Offline continuity","Queued previews and evidence","Physical proof tools","Notifications","Field operations"],tasks:["Show remote versus fallback surface","Preserve cached snapshot","Retry sync on focus and reconnect","Keep Sovereign Stop reachable","Support physical evidence adapters","Complete real-phone acceptance"],gate:"Current remote overlay is public-safe and read-only; F07 physical acceptance remains open."},
    settings:{id:"OM-P20",route:"/operations/settings",phase:"DELIVERY PATHWAY",purpose:"Manage product, device, network, security and privacy settings.",zones:["Product identity","Interface preferences","Device storage","Network policy","Security policy","Privacy and diagnostics"],tasks:["State scope and default for every setting","Provide recovery path","Expose delivery diagnostics","Test local storage and proof export","Keep package and source identities separate"],gate:"Native policy changes still require a signed APK; UI/data changes auto-sync."},
    release:{id:"OM-P21",route:"/operations/release",phase:"DELIVERY PATHWAY",purpose:"Promote exact, evidenced and recoverable releases.",zones:["Release candidate","Evidence checklist","Known limitations","Approval chain","Promotion ceremony","Final receipt"],tasks:["Verify source, artifact and signer","Require test, security, runtime, proof, memory and recovery evidence","Preserve limitations","Require typed or biometric approval","Append lineage and recovery coordinate"],gate:"No promotion with missing, stale, contradictory or mismatched evidence."},
    console:{id:"OM-P22",route:"/operations/console",phase:"OBSERVABILITY CORE",purpose:"Expose raw product and diagnostic truth.",zones:["Raw state browser","Correlated logs","Integrity checks","Native bridge diagnostics","Delivery state","Support export"],tasks:["Expose source and package identity","Show current sync version","Validate workspace and organ counts","Preserve errors","Export safe diagnostics","Operate offline"],gate:"First page in the clearance order because all later rooms depend on observable truth."}
  });

  const css = `
  .omni-sync-blueprint{margin:0 0 10px;border:1px solid rgba(53,217,255,.45);border-radius:17px;background:linear-gradient(150deg,rgba(8,30,43,.98),rgba(7,13,21,.98));box-shadow:0 18px 55px rgba(0,0,0,.32);overflow:hidden}
  .omni-sync-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:13px 14px;border-bottom:1px solid rgba(53,217,255,.18)}
  .omni-sync-head small{display:block;color:#35d9ff;font-size:7px;letter-spacing:.14em;font-weight:900;margin-bottom:4px}.omni-sync-head h2{margin:0;font-size:15px}.omni-sync-badge{border:1px solid #245d71;border-radius:999px;color:#35d9ff;padding:6px 8px;font-size:7px;font-weight:900;white-space:nowrap}
  .omni-sync-body{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:9px;padding:11px}.omni-sync-block{border:1px solid #203248;border-radius:12px;background:rgba(4,9,15,.62);padding:10px}.omni-sync-block b{display:block;font-size:9px;margin-bottom:6px}.omni-sync-block p{margin:0;color:#9dafc1;font-size:8px;line-height:1.5}.omni-sync-block ul{margin:0;padding-left:16px;color:#9dafc1;font-size:8px;line-height:1.55}.omni-sync-foot{display:flex;gap:6px;overflow:auto;padding:0 11px 11px}.omni-sync-foot span{border:1px solid #203248;border-radius:999px;padding:6px 8px;font-size:7px;white-space:nowrap;color:#8293aa}.omni-sync-foot .ok{color:#4ade80;border-color:#24593a}.omni-sync-foot .gate{color:#fbbf24;border-color:#66531e}
  @media(max-width:900px){.omni-sync-body{grid-template-columns:1fr 1fr}}@media(max-width:720px){.omni-sync-body{grid-template-columns:1fr}.omni-sync-head h2{font-size:13px}}
  `;

  function injectCss(){
    if(document.getElementById("omni-remote-overlay-css")) return;
    const style=document.createElement("style");style.id="omni-remote-overlay-css";style.textContent=css;document.head.appendChild(style);
  }

  function activePage(){
    return document.querySelector("#nav button.active")?.dataset.view || document.querySelector("[data-mobile].active")?.dataset.mobile || "home";
  }

  function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
  function list(items){return `<ul>${items.map(item=>`<li>${escapeHtml(item)}</li>`).join("")}</ul>`;}

  function renderBlueprint(){
    const content=document.getElementById("content");if(!content) return;
    const key=activePage();const page=PAGE[key]||PAGE.home;
    let panel=document.getElementById("omni-sync-blueprint");
    if(!panel){panel=document.createElement("section");panel.id="omni-sync-blueprint";panel.className="omni-sync-blueprint";content.prepend(panel);}
    panel.innerHTML=`<div class="omni-sync-head"><div><small>${escapeHtml(page.phase)} · ${escapeHtml(page.id)} · ${escapeHtml(page.route)}</small><h2>${escapeHtml(page.purpose)}</h2></div><span class="omni-sync-badge">AUTO-SYNC ${escapeHtml(VERSION)}</span></div><div class="omni-sync-body"><div class="omni-sync-block"><b>ROOM ZONES</b>${list(page.zones)}</div><div class="omni-sync-block"><b>CONSTRUCTION TASKS</b>${list(page.tasks)}</div><div class="omni-sync-block"><b>CLEARANCE GATE</b><p>${escapeHtml(page.gate)}</p></div></div><div class="omni-sync-foot"><span class="ok">REMOTE BLUEPRINT ONLINE</span><span class="ok">22 WORKSPACES REGISTERED</span><span>MOTHERSHIP ${escapeHtml((manifest.mothership_source_sha||"UNAVAILABLE").slice(0,12))}</span><span>JANUS ${escapeHtml((manifest.janus_source_sha||"UNAVAILABLE").slice(0,12))}</span><span class="gate">F02 PHYSICAL GATE</span><span class="ok">EMBEDDED FALLBACK READY</span></div>`;
  }

  function updateChrome(){
    const ribbon=document.querySelector(".ribbon");
    if(ribbon) ribbon.innerHTML=`<span class="pulse" style="background:#4ade80;box-shadow:0 0 13px #4ade80"></span><b>AUTO-SYNC BLUEPRINT ONLINE</b><span>OmniMind 4.0.2 · Mothership ${(manifest.mothership_source_sha||"UNAVAILABLE").slice(0,12)} · offline fallback preserved</span>`;
    const rail=document.querySelector(".rail");
    if(rail) rail.innerHTML=`<span class="chip green">AUTO-SYNC ONLINE</span><span class="chip cyan">MOTHERSHIP ${(manifest.mothership_source_sha||"UNAVAILABLE").slice(0,8)}</span><span class="chip green">22 WORKSPACES</span><span class="chip amber">F02 PHYSICAL GATE</span><span class="chip green">OFFLINE FALLBACK READY</span>`;
    const foot=document.querySelector(".sidefoot");if(foot) foot.innerHTML=`REMOTE BLUEPRINT SYNCHRONIZED<br><span style="color:#4ade80">${escapeHtml(VERSION)}</span> · local cockpit retained`;
  }

  injectCss();updateChrome();renderBlueprint();
  let queued=false;
  const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;updateChrome();renderBlueprint();});});
  observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});
  window.addEventListener("hashchange",renderBlueprint);
  window.dispatchEvent(new CustomEvent("omnimind:remote-overlay-ready",{detail:{version:VERSION,page_count:Object.keys(PAGE).length}}));
})();
